# Generated by Django 3.2 on 2022-01-24 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appt',
        ),
    ]
