# Generated by Django 3.2 on 2022-01-16 21:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
            options={
                'ordering': ['coach_name'],
            },
        ),
    ]
